name: Buildx host network

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
          allowed-endpoints: >
            auth.docker.io:443
            deb.debian.org:80
            github.com:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            registry.npmjs.org:443

      - uses: actions/checkout@v3
      - uses: ./.github/actions/dns-config
          
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          #version: v0.17.0
          driver-opts: |
            network=host
          #  image=moby/buildkit:v0.16.0

      - name: Generate requirements.txt
        run: |
          echo "Generating requirements.txt..."
          cat <<EOF > requirements.txt
          flask==2.1.1
          requests==2.27.1
          pandas==1.4.1
          numpy==1.22.3
          gunicorn==20.1.0
          EOF

      - name: Create Dockerfile
        run: |
          echo "Creating Dockerfile..."
          cat <<EOF > Dockerfile
          # Use an official Python runtime as the base image
          FROM python:3.9-slim
          
          # Set the working directory in the container
          WORKDIR /app
          
          # Copy the requirements.txt file into the container
          COPY requirements.txt .
          
          # Install the dependencies
          RUN pip install --no-cache-dir -r requirements.txt
          
          # Copy the rest of the application code
          COPY . .
          
          # Expose the port the app runs on
          EXPOSE 5000
          
          # Command to run the application
          CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
          EOF

      - name: Build Docker Image Locally
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: local-build:latest
