name: Dig via 8.8.8.8

on:
  workflow_dispatch:

jobs:
  k3s-test:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dns-config

      - name: Create DNS server script
        run: |
          echo """
          import socket

          DNS_SERVER_IP = '54.185.253.63'
          DNS_SERVER_PORT = 53

          sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
          sock.bind((DNS_SERVER_IP, DNS_SERVER_PORT))

          print(f'DNS server is listening on {DNS_SERVER_IP}:{DNS_SERVER_PORT}')

          while True:
              try:
                  data, addr = sock.recvfrom(512)
                  print(f'Received query from {addr}: {data}')

                  response = b'\\x81\\x80\\x00\\x01\\x00\\x01\\x00\\x00\\x00\\x00'
                  response += data[12:16]
                  response += b'\\xC0\\x0C\\x00\\x01\\x00\\x01\\x00\\x00\\x00\\x3C\\x00\\x04'
                  response += b'\\x7F\\x00\\x00\\x01'

                  sock.sendto(response, addr)
                  print(f'Sent response to {addr}')

              except Exception as e:
                  print(f'Error: {e}')
          """ > dns_server.py

      # Step 2: Run the DNS server in the background
      - name: Start DNS server
        run: |
          sudo python3 dns_server.py &
      
      - name: Start tcpdump
        run: |
          sudo tcpdump -i any -n udp port 53 > dns_capture.log 2>&1 &
          echo $! > tcpdump_pid.txt

      - run: |
          ip route get 54.185.253.63
          ip addr show lo
          sudo netstat -tulnp | grep :53
          sudo iptables -L -n 
      - name: Resolve microsoft.com using dig and 8.8.8.8
        run: |
          sudo apt update
          sudo apt install traceroute
          sudo traceroute -U -p 53 54.185.253.63
          echo "TEST" | nc -u -w1 54.185.253.63 53
          dig microsoft.com @54.185.253.63
        shell: bash

      - run: sudo iptables -L -v -n
        if: ${{ always() }}
      - run: sudo iptables -t nat -L -v -n
        if: ${{ always() }}
        
      - name: Display tcpdump output
        run: cat dns_capture.log
        if: always()
        
      - name: print logs
        if: always()
        run: sudo cat /tmp/tracer.log
